name: xgb2
channels:
  - anaconda
  - nodefaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - jupyterlab=3.5.2
  - libffi=3.4.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.10.13
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - adata==1.1.1
      - anndata==0.10.2
      - array-api-compat==1.4
      - asttokens==2.4.0
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.1
      - colorama==0.4.6
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - dill==0.3.7
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - fonttools==4.43.1
      - h5py==3.10.0
      - idna==3.4
      - igraph==0.10.8
      - imbalanced-learn==0.11.0
      - iprogress==0.4
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - leidenalg==0.10.1
      - llvmlite==0.41.0
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - natsort==8.4.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2
      - numba==0.58.0
      - numpy==1.23.5
      - packaging==23.2
      - pandas==2.1.1
      - parso==0.8.3
      - patsy==0.5.3
      - pickleshare==0.7.5
      - pillow==10.1.0
      - platformdirs==3.11.0
      - plotly==5.17.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - pure-eval==0.2.2
      - py-mini-racer==0.6.0
      - pyaml==23.9.7
      - pygments==2.16.1
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - requests==2.31.0
      - rpds-py==0.10.6
      - scanpy==1.9.5
      - scikit-learn==1.3.1
      - scikit-network==0.31.0
      - scikit-optimize==0.9.0
      - scipy==1.11.3
      - seaborn==0.13.0
      - session-info==1.0.0
      - six==1.16.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - tenacity==8.2.3
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.8.1
      - tzdata==2023.3
      - umap-learn==0.5.4
      - urllib3==2.0.7
      - wcwidth==0.2.8
      - widgetsnbextension==4.0.9
      - xgboost==2.0.0

