name: OrgIP
channels:
  - anaconda
  - nodefaults
  - conda-forge
dependencies:
  - attrs=22.1.0
  - cffi=1.15.1
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - jupyter_client=7.4.8
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - libffi=3.4.2
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - pip=22.3.1
  - python=3.10.9
  - pytz=2022.7
  - requests=2.28.1
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - tornado=6.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - pydantic
  - pytomlpp
  - pyyaml
  - appdirs
  - pip:
      - anndata==0.8.0
      - bokeh==2.4.3
      - colorcet==3.0.1
      - dash==2.13.0
      - dash-bio==1.0.2
      - datashader==0.14.4
      - decorator==5.1.1
      - fastcluster==1.2.6
      - datashader==0.14.4
      - holoviews==1.15.4
      - ipykernel==6.20.1
      - ipywidgets==7.7.1
      - jupyter-core==5.1.3
      - jupyterlab-widgets==3.0.5
      - keras==2.11.0
      - leidenalg==0.9.1
      - matplotlib==3.5.3
      - matplotlib-venn==0.11.9
      - numba==0.56.4
      - numpy==1.23.5
      - openpyxl==3.1.2
      - pandas==1.3.5
      - plotly==5.11.0
      - pysankeybeta==1.4.1
      - python-ternary==1.0.8
      - scanpy==1.9.1
      - scikit-image==0.20.0
      - scikit-learn==1.2.0
      - scikit-network==0.28.3
      - scipy==1.10.0
      - seaborn==0.12.2
      - statsmodels==0.13.5
      - umap-learn==0.5.3
